name: k6 Load Test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up k6
        uses: grafana/setup-k6@v1
        with:
          k6-version: "latest"

      - name: Run k6 test
        run: k6 run K6/test-plans/Blaze-demo-test.js
