name: k6 Load Test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:gophers/archive
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run k6 test
        run: k6 run K6/test-plans/Blaze-demo-test.js
